###################################################################################################################################
###### Default Labels - These really didn't fit into any other section.
###################################################################################################################################

- name: good first issue
  color: '333333'
  description: 'Issues that are good entry points for newcomers.'

- name: help wanted
  color: '555555'
  description: 'Issues where the maintainers need additional help or input.'
  
###################################################################################################################################
###### Area - This is used to label PRs, by which paths / files / areas are updated.
###################################################################################################################################
- name: needs-area
  color: 'FFFFFF'  # White for needs-kind
  description: 'Indicates a PR is msising an area label'
  
- name: area/dependency
  color: 'E99695'
  description: 'PR updates dependancies'
  aliases:
    - dependencies
    
- name: area/documentation
  color: 'E99695'
  description: 'PR updates documentation'

- name: area/deployment/docker-compose
  color: 'E99695'
  description: 'PR updates docker-compose files'

- name: area/deployment/kubernetes
  color: 'E99695'
  description: 'PR updates kubernetes manifests'
  
- name: area/deployment/helm
  color: 'E99695'
  description: 'PR updates helm charts'
  
- name: area/github/templates
  color: 'E99695'
  description: 'PR updates github templates'
  
- name: area/github/workflow
  color: 'E99695'
  description: 'PR updates github workflows'

- name: area/testing
  color: 'E99695'
  description: 'PR updates unit / integration testing'
 
###################################################################################################################################
###### Kind - Indicates what "kind" of issue/PR this is. Aka, feature, bug, cleanup, documentation, etc...
###################################################################################################################################

- name: needs-kind
  color: 'FFFFFF'  # White for needs-kind
  description: 'Indicates a pull request or issue lacks a specific `kind` label and requires one.'
  
- name: kind/bug
  color: 'B22222'  # Dark red for bugs
  description: 'Issues where something is not working as intended.'
  aliases:
    - bug

- name: kind/cleanup
  color: '006B75'
  description: 'Tasks related to cleaning up code, processes, or technical debt.'

- name: kind/deprecation
  color: '006B75'
  description: 'Features or enhancements that are marked for future deprecation.'

- name: kind/documentation
  color: '006B75'
  description: 'Improvements or additions to project documentation.'
  aliases:
    - documentation

- name: kind/feature
  color: '006B75'
  description: 'Issues or pull requests related to new features.'

- name: kind/support
  color: '006B75'
  description: 'Issues or pull requests related to support questions.'
  aliases:
    - question

###################################################################################################################################
###### Lifecycle / State - This is the current state of an issue. Active, Stale, Frozen, Rotten.
###### Flow: new -> active -> stale -> rotten -> auto-closed.
###### Add lifecycle/frozen, to disable automatic lifecycle.
###################################################################################################################################
- name: lifecycle/new
  color: '28A745'  # Green for active
  description: 'Issues or pull requests that are currently being actively worked on.'
  
- name: lifecycle/active
  color: '28A745'  # Green for active
  description: 'Issues or pull requests that are currently being actively worked on.'

- name: lifecycle/frozen
  color: 'FBCA04'
  description: 'Issues or pull requests that should not be auto-closed due to inactivity.'

- name: lifecycle/rotten
  color: 'FBCA04'
  description: 'Issues eligable for auto-closure due to extended inactivity.'

- name: lifecycle/stale
  color: 'FBCA04'
  description: 'Issues or pull requests that have become inactive and need attention.'
  
###################################################################################################################################
###### Priority, Indicates the priority of a particular issue or PR.
###### New / Un-triaged tickets will be needs-priority.
###### Order: unplanned -> low -> normal -> high -> urgent
###################################################################################################################################

- name: needs-priority
  color: 'FFFFFF'  # White for needs-triage
  description: 'Indicates a pull request or issue lacks a specific `triage` label and requires one.'
  aliases:
    - priority/awaiting-more-evidence

- name: priority/unplanned
  color: 'D93F0B'
  description: 'Feature or issue deemed valid, however, not currently planned.'
  
- name: priority/low
  color: 'D93F0B'
  description: 'Low priority'
  
- name: priority/normal
  color: 'D93F0B'
  description: 'Feature or issue planned for future implementation.'
  aliases:
    - priority/backlog
    
- name: priority/high
  color: 'D93F0B'
  description: 'Issues or features that are important and need attention soon.'
  aliases:
    - priority/important
    
- name: priority/urgent
  color: 'FF0000'  # Red for urgent
  description: 'Issues or features that require immediate resolution.'

###################################################################################################################################
###### Triage - This is used to categorize incoming tickets, to determine validity.
###### New / Un-triaged tickets will be set to needs-triage
###################################################################################################################################

- name: needs-triage
  color: 'FFFFFF'  # White for needs-triage
  description: 'Indicates a pull request or issue lacks a specific `triage` label and requires one.'
  
- name: triage/accepted
  color: '28A745'  # Green for accepted
  description: 'Issues or pull requests that are accepted and being worked on.'

- name: triage/duplicate
  color: '5319E7'
  description: 'Indicates that this issue or pull request is a duplicate of an existing one.'
  aliases:
    - duplicate

- name: triage/needs-information
  color: '5319E7'
  description: 'Issues or pull requests that require additional information to proceed.'

- name: triage/non-reproducible
  color: '5319E7'
  description: 'Issues that cannot be reproduced and need further investigation.'

- name: triage/unresolved
  color: '5319E7'
  description: 'Issues that cannot be resolved.'

- name: triage/wont-fix
  color: '5319E7'
  description: 'Indicates that this issue or pull request will not be worked on.'
  aliases:
    - wontfix
