site_name: WarBOT
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - git-revision-date-localized
#   - privacy

repo_url: https://github.com/XtremeOwnage/WarBot
repo_name: WarBOT

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://static.xtremeownage.com/discord
      name: Discord
    - icon: fontawesome/brands/github 
      link: https://github.com/XtremeOwnage/WarBot
      name: WarBOT Github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
