// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarBot.Storage;

namespace WarBot.Storage.Migrations
{
    [DbContext(typeof(WarDB))]
    partial class WarDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview1-35029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WarBot.Storage.Models.DiscordGuild", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BotVersion");

                    b.Property<decimal>("EntityId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<int>("Environment");

                    b.Property<string>("Loot");

                    b.Property<string>("Name");

                    b.Property<long?>("NotificationSettingsID");

                    b.Property<string>("WarBOT_NickName");

                    b.Property<string>("WarBOT_Prefix");

                    b.Property<string>("Website");

                    b.HasKey("ID");

                    b.HasIndex("NotificationSettingsID");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("WarBot.Storage.Models.DiscordUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("EntityId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<DateTimeOffset?>("LastActivity");

                    b.Property<DateTimeOffset?>("LastOnline");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildChannel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelType");

                    b.Property<decimal>("EntityId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<int?>("GuildID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("GuildID");

                    b.ToTable("GuildChannel");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildNotificationsSettings", b =>
                {
                    b.Property<long>("ID");

                    b.Property<string>("GreetingMessage");

                    b.Property<bool>("SendUpdateMessage");

                    b.Property<bool>("War1Enabled");

                    b.Property<bool>("War2Enabled");

                    b.Property<bool>("War3Enabled");

                    b.Property<bool>("War4Enabled");

                    b.Property<bool>("WarPrepEnding");

                    b.Property<string>("WarPrepEndingMessage");

                    b.Property<bool>("WarPrepStarted");

                    b.Property<string>("WarPrepStartedMessage");

                    b.Property<bool>("WarStarted");

                    b.Property<string>("WarStartedMessage");

                    b.HasKey("ID");

                    b.ToTable("GuildNotificationsSettings");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("EntityId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<int?>("GuildID");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("GuildID");

                    b.ToTable("GuildRole");
                });

            modelBuilder.Entity("WarBot.Storage.Models.HustleCastle.HustleGuild", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DiscordGuildId");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("DiscordGuildId")
                        .IsUnique()
                        .HasFilter("[DiscordGuildId] IS NOT NULL");

                    b.ToTable("HustleGuild");
                });

            modelBuilder.Entity("WarBot.Storage.Models.HustleCastle.HustleGuildSeason", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("DateEnd");

                    b.Property<int?>("HustleGuildID");

                    b.Property<int?>("HustleUserID");

                    b.Property<long>("MinimumGameGlory");

                    b.Property<long>("MinimumGuildGlory");

                    b.HasKey("ID");

                    b.HasIndex("HustleGuildID");

                    b.HasIndex("HustleUserID");

                    b.ToTable("HustleGuildSeason");
                });

            modelBuilder.Entity("WarBot.Storage.Models.HustleCastle.HustleUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int?>("HustleGuildID");

                    b.Property<bool>("IsActiveCharacter");

                    b.Property<DateTimeOffset>("JoinDate");

                    b.Property<long>("SquadPower");

                    b.Property<byte>("ThroneRoomLevel");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("HustleGuildID");

                    b.HasIndex("UserID");

                    b.ToTable("HustleUser");
                });

            modelBuilder.Entity("WarBot.Storage.Models.HustleCastle.HustleUserSeason", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Glory");

                    b.Property<int?>("SeasonID");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("SeasonID");

                    b.HasIndex("UserID");

                    b.ToTable("HustleUserSeason");
                });

            modelBuilder.Entity("WarBot.Storage.Models.HustleCastle.LootItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("HustleGuildSeasonID");

                    b.Property<int?>("HustleUserSeasonID");

                    b.Property<int?>("HustleUserSeasonID1");

                    b.Property<string>("Name");

                    b.Property<int?>("WinningUserID");

                    b.HasKey("ID");

                    b.HasIndex("HustleGuildSeasonID");

                    b.HasIndex("HustleUserSeasonID");

                    b.HasIndex("HustleUserSeasonID1");

                    b.HasIndex("WinningUserID");

                    b.ToTable("LootItem");
                });

            modelBuilder.Entity("WarBot.Storage.Models.DiscordGuild", b =>
                {
                    b.HasOne("WarBot.Storage.Models.GuildNotificationsSettings", "NotificationSettings")
                        .WithMany()
                        .HasForeignKey("NotificationSettingsID");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildChannel", b =>
                {
                    b.HasOne("WarBot.Storage.Models.DiscordGuild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildID");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildRole", b =>
                {
                    b.HasOne("WarBot.Storage.Models.DiscordGuild", "Guild")
                        .WithMany("Roles")
                        .HasForeignKey("GuildID");
                });

            modelBuilder.Entity("WarBot.Storage.Models.HustleCastle.HustleGuild", b =>
                {
                    b.HasOne("WarBot.Storage.Models.DiscordGuild", "DiscordGuild")
                        .WithOne("HustleClan")
                        .HasForeignKey("WarBot.Storage.Models.HustleCastle.HustleGuild", "DiscordGuildId");
                });

            modelBuilder.Entity("WarBot.Storage.Models.HustleCastle.HustleGuildSeason", b =>
                {
                    b.HasOne("WarBot.Storage.Models.HustleCastle.HustleGuild")
                        .WithMany("Seasons")
                        .HasForeignKey("HustleGuildID");

                    b.HasOne("WarBot.Storage.Models.HustleCastle.HustleUser")
                        .WithMany("Seasons")
                        .HasForeignKey("HustleUserID");
                });

            modelBuilder.Entity("WarBot.Storage.Models.HustleCastle.HustleUser", b =>
                {
                    b.HasOne("WarBot.Storage.Models.HustleCastle.HustleGuild")
                        .WithMany("Users")
                        .HasForeignKey("HustleGuildID");

                    b.HasOne("WarBot.Storage.Models.DiscordUser", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WarBot.Storage.Models.HustleCastle.HustleUserSeason", b =>
                {
                    b.HasOne("WarBot.Storage.Models.HustleCastle.HustleGuildSeason", "Season")
                        .WithMany("UserData")
                        .HasForeignKey("SeasonID");

                    b.HasOne("WarBot.Storage.Models.HustleCastle.HustleUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("WarBot.Storage.Models.HustleCastle.LootItem", b =>
                {
                    b.HasOne("WarBot.Storage.Models.HustleCastle.HustleGuildSeason")
                        .WithMany("AvailableLoot")
                        .HasForeignKey("HustleGuildSeasonID");

                    b.HasOne("WarBot.Storage.Models.HustleCastle.HustleUserSeason")
                        .WithMany("GreedItems")
                        .HasForeignKey("HustleUserSeasonID");

                    b.HasOne("WarBot.Storage.Models.HustleCastle.HustleUserSeason")
                        .WithMany("NeedItems")
                        .HasForeignKey("HustleUserSeasonID1");

                    b.HasOne("WarBot.Storage.Models.HustleCastle.HustleUser", "WinningUser")
                        .WithMany()
                        .HasForeignKey("WinningUserID");
                });
#pragma warning restore 612, 618
        }
    }
}
