// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarBot.Storage;

namespace WarBot.Storage.Migrations
{
    [DbContext(typeof(WarDB))]
    partial class WarDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("WarBot.Storage.Models.Guild", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ConfigId");

                    b.Property<string>("Name");

                    b.HasKey("GuildId");

                    b.HasIndex("ConfigId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildChannel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChannelType");

                    b.Property<ulong?>("EntityId");

                    b.Property<int?>("GuildConfigID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("GuildConfigID");

                    b.ToTable("GuildChannel");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildConfig", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BotVersion");

                    b.Property<int>("Environment");

                    b.Property<int?>("GuildNotificationSettingsId");

                    b.Property<string>("Loot");

                    b.Property<string>("Website");

                    b.HasKey("ID");

                    b.HasIndex("GuildNotificationSettingsId");

                    b.ToTable("GuildConfig");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildNotificationsConfig", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("SendUpdateMessage");

                    b.Property<bool>("War1Enabled");

                    b.Property<bool>("War2Enabled");

                    b.Property<bool>("War3Enabled");

                    b.Property<bool>("War4Enabled");

                    b.Property<bool>("WarPrepAlmostOver");

                    b.Property<string>("WarPrepEndingMessage");

                    b.Property<bool>("WarPrepStarted");

                    b.Property<string>("WarPrepStartedMessage");

                    b.Property<bool>("WarStarted");

                    b.Property<string>("WarStartedMessage");

                    b.HasKey("ID");

                    b.ToTable("GuildNotificationsConfig");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong?>("EntityId");

                    b.Property<int?>("GuildConfigID");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("GuildConfigID");

                    b.ToTable("GuildRole");
                });

            modelBuilder.Entity("WarBot.Storage.Models.User", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WarBot.Storage.Models.Guild", b =>
                {
                    b.HasOne("WarBot.Storage.Models.GuildConfig", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildChannel", b =>
                {
                    b.HasOne("WarBot.Storage.Models.GuildConfig", "GuildConfig")
                        .WithMany("Channels")
                        .HasForeignKey("GuildConfigID");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildConfig", b =>
                {
                    b.HasOne("WarBot.Storage.Models.GuildNotificationsConfig", "NotificationSettings")
                        .WithMany()
                        .HasForeignKey("GuildNotificationSettingsId");
                });

            modelBuilder.Entity("WarBot.Storage.Models.GuildRole", b =>
                {
                    b.HasOne("WarBot.Storage.Models.GuildConfig", "GuildConfig")
                        .WithMany("Roles")
                        .HasForeignKey("GuildConfigID");
                });
#pragma warning restore 612, 618
        }
    }
}
