{{- if .Values.networkPolicies.enabled -}}
{{- range .Values.networkPolicies.policies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "warbot.labels" $ | nindent 4 }}
spec:
  podSelector:
    {{- toYaml .podSelector | nindent 4 }}
  policyTypes:
  {{- if .ingress }}
  - Ingress
  {{- end }}
  {{- if .egress }}
  - Egress
  {{- end }}
  {{- if .ingress }}
  ingress:
  {{- range .ingress }}
  - from:
    {{- toYaml .from | nindent 6 }}
  {{- end }}
  {{- end }}
  {{- if .egress }}
  egress:
  {{- range .egress }}
  - to:
    {{- toYaml .to | nindent 6 }}
    ports:
    {{- toYaml .ports | nindent 6 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
