name: Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.5.0

    - name: Package Helm Chart
      run: |
        helm package deployment/helm/warbot
        helm repo index . --url https://XtremeOwnage.github.io/WarBot/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
