name: Sync labels
on:
  # Allow manually triggering this job.
  workflow_dispatch:
  
permissions:
  # This job will need write permissions to issues (to manage labels)
  issues: write
  
jobs:
  sync:
    # This job syncs labels from an upstream template repo.
    name: Sync Labels    
    runs-on: ubuntu-latest
    steps:
    - uses: EndBug/label-sync@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
        # Use config from a repository containing defaults.
        config-file: https://raw.githubusercontent.com/XtremeOwnage/Template/main/.github/workflows/sync-upstream-repo.yml

        # If you want the action just to show you the preview of the changes, without actually editing the labels, set this to true
        dry-run: true
