name: Sync labels
on:
  # Allow manually triggering this job.
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Should a dry-run be performed? Will not perform any changes."
        required: false
        default: false
        type: boolean
        
permissions:
  # This job will need write permissions to issues (to manage labels)
  issues: write
  
jobs:
  sync:
    # This job syncs labels from an upstream template repo.
    name: Sync Labels    
    runs-on: ubuntu-latest
    steps:
    - uses: EndBug/label-sync@v2
      with:
        # Use config from a repository containing defaults.
        config-file: https://raw.githubusercontent.com/XtremeOwnage/Defaults/main/.github/labels.yml

        # If you want the action just to show you the preview of the changes, without actually editing the labels, set this to true
        dry-run: ${{ inputs.dry-run }}
